/** Mock Data presets — kept separate (no imports) so the category module can use them as examples cheaply. */
type MockField = { name: string; type: string; [k: string]: unknown };

/* ── presets ────────────────────────────────────────────────────────── */

const S = (fields: MockField[]) => JSON.stringify({ fields }, null, 2);

export const PRESETS: Record<string, string> = {
  users: S([
    { name: "id", type: "increment" },
    { name: "first_name", type: "firstName" },
    { name: "last_name", type: "lastName" },
    { name: "email", type: "email", unique: true },
    { name: "username", type: "username" },
    { name: "age", type: "age", min: 18, max: 75 },
    { name: "city", type: "city" },
    { name: "country", type: "countryCode" },
    { name: "plan", type: "enum", values: "free:60,pro:30,enterprise:10" },
    { name: "active", type: "bool", prob: 85 },
    { name: "signed_up", type: "date", from: "2022-01-01", to: "2025-12-31" },
    { name: "phone", type: "phone", nullable: 20 },
  ]),
  orders: S([
    { name: "order_id", type: "pattern", pattern: "ORD-2025-#####", unique: true },
    { name: "customer", type: "fullName" },
    { name: "email", type: "email" },
    { name: "product", type: "product" },
    { name: "unit_price", type: "price", min: 5, max: 400 },
    { name: "quantity", type: "int", min: 1, max: 6 },
    { name: "subtotal", type: "formula", formula: "round(unit_price * quantity, 2)" },
    { name: "tax", type: "formula", formula: "round(subtotal * 0.2, 2)" },
    { name: "total", type: "formula", formula: "round(subtotal + tax, 2)" },
    { name: "status", type: "enum", values: "delivered:55,shipped:20,processing:15,cancelled:6,refunded:4" },
    { name: "ordered_at", type: "datetime", from: "2025-01-01", to: "2025-12-31" },
  ]),
  products: S([
    { name: "sku", type: "pattern", pattern: "[A-Z]{3}-####", unique: true },
    { name: "name", type: "product" },
    { name: "department", type: "department" },
    { name: "price", type: "price", min: 2, max: 900 },
    { name: "cost", type: "formula", formula: "round(price * 0.55, 2)" },
    { name: "margin_pct", type: "formula", formula: "round((price - cost) / price * 100, 1)" },
    { name: "stock", type: "int", min: 0, max: 500 },
    { name: "in_stock", type: "formula", formula: "stock > 0" },
    { name: "rating", type: "float", min: 1, max: 5, decimals: 1 },
    { name: "colour", type: "colorName" },
    { name: "discontinued", type: "bool", prob: 8 },
  ]),
  transactions: S([
    { name: "txn_id", type: "uuid" },
    { name: "account", type: "iban" },
    { name: "type", type: "enum", values: "debit:65,credit:30,fee:5" },
    { name: "amount", type: "amount", min: 1, max: 2500, decimals: 2 },
    { name: "signed_amount", type: "formula", formula: 'type == "credit" ? amount : -amount' },
    { name: "currency", type: "enum", values: "GBP:50,EUR:30,USD:20" },
    { name: "merchant", type: "company" },
    { name: "card", type: "pattern", pattern: "•••• •••• •••• ####" },
    { name: "booked_at", type: "datetime", from: "2025-06-01", to: "2025-06-30" },
    { name: "flagged", type: "bool", prob: 3 },
  ]),
  iot: S([
    { name: "reading_id", type: "increment", min: 100000 },
    { name: "device", type: "pattern", pattern: "sensor-[a-f0-9]{6}" },
    { name: "site", type: "enum", values: "warehouse-a,warehouse-b,cold-store,loading-bay" },
    { name: "recorded_at", type: "datetime", from: "2025-09-01", to: "2025-09-02" },
    { name: "temperature_c", type: "float", min: -4, max: 31, decimals: 2 },
    { name: "humidity_pct", type: "float", min: 20, max: 90, decimals: 1 },
    { name: "battery_pct", type: "int", min: 5, max: 100 },
    { name: "alert", type: "formula", formula: "temperature_c > 28 || battery_pct < 10" },
    { name: "lat", type: "latitude" },
    { name: "lng", type: "longitude" },
    { name: "firmware", type: "semver" },
  ]),
  posts: S([
    { name: "id", type: "increment" },
    { name: "title", type: "title" },
    { name: "slug", type: "formula", formula: "slug(title)" },
    { name: "author", type: "fullName" },
    { name: "author_email", type: "email" },
    { name: "excerpt", type: "sentence" },
    { name: "body", type: "paragraph" },
    { name: "tags", type: "enum", values: "javascript,devops,design,career,databases,security" },
    { name: "published", type: "bool", prob: 75 },
    { name: "published_at", type: "datetime", from: "2024-01-01", to: "2025-12-31", nullable: 25 },
    { name: "views", type: "int", min: 0, max: 50000 },
    { name: "likes", type: "formula", formula: "floor(views * 0.04)" },
  ]),
  employees: S([
    { name: "employee_id", type: "pattern", pattern: "E####", unique: true },
    { name: "first_name", type: "firstName" },
    { name: "last_name", type: "lastName" },
    { name: "full_name", type: "formula", formula: 'concat(first_name, " ", last_name)' },
    { name: "email", type: "companyEmail" },
    { name: "job_title", type: "jobTitle" },
    { name: "department", type: "enum", values: "Engineering:35,Sales:20,Support:15,Marketing:10,Finance:10,HR:10" },
    { name: "salary", type: "int", min: 32000, max: 165000 },
    { name: "hired", type: "date", from: "2012-01-01", to: "2025-06-30" },
    { name: "remote", type: "bool", prob: 40 },
    { name: "manager_id", type: "pattern", pattern: "E####", nullable: 10 },
  ]),
};
