// Generated from docs/design/tools-registry-data.js — every Phosphor icon the app names.
// Duotone is the house weight; see ToolIcon.
import {
  ArrowRight,
  ArrowUDownLeft,
  ArrowUp,
  ArrowsInLineHorizontal,
  Article,
  Asterisk,
  BezierCurve,
  Binary,
  Blueprint,
  BracketsAngle,
  BracketsCurly,
  BracketsSquare,
  CalendarDots,
  CardsThree,
  CaretDown,
  Certificate,
  ChartBar,
  CircleHalf,
  ClipboardText,
  ClockCountdown,
  ClockCounterClockwise,
  CloudArrowDown,
  Code,
  Copy,
  Cube,
  CubeTransparent,
  Database,
  DiamondsFour,
  DownloadSimple,
  Eraser,
  EyeSlash,
  Eyedropper,
  FileCode,
  FileJs,
  FilePdf,
  FilePy,
  FileText,
  Fingerprint,
  Flask,
  FlowArrow,
  Folders,
  Funnel,
  GearSix,
  GitBranch,
  GitDiff,
  GlobeHemisphereWest,
  Graph,
  GridFour,
  HashStraight,
  IdentificationCard,
  Image,
  Infinity,
  Info,
  Key,
  Lightning,
  Link,
  LinkBreak,
  LinkSimple,
  List,
  ListBullets,
  MagnifyingGlass,
  NumberSquareTwo,
  PaintBrush,
  PaintBrushBroad,
  PaperPlaneTilt,
  Password,
  Path,
  PencilSimple,
  Play,
  Plugs,
  Plus,
  QrCode,
  Quotes,
  Ruler,
  Scribble,
  SealCheck,
  ShieldCheck,
  ShippingContainer,
  Shuffle,
  SidebarSimple,
  Sliders,
  Square,
  Star,
  Table,
  TerminalWindow,
  TextAa,
  TextAlignLeft,
  TextH,
  Timer,
  Trash,
  TreeStructure,
  TreeView,
  WarningCircle,
  WifiSlash,
  Wrench,
  X,
} from "@phosphor-icons/react/dist/ssr";
import type { Icon } from "@phosphor-icons/react";

export const ICONS: Record<string, Icon> = {
  "arrow-right": ArrowRight,
  "arrow-u-down-left": ArrowUDownLeft,
  "arrow-up": ArrowUp,
  "arrows-in-line-horizontal": ArrowsInLineHorizontal,
  "article": Article,
  "asterisk": Asterisk,
  "bezier-curve": BezierCurve,
  "binary": Binary,
  "blueprint": Blueprint,
  "brackets-angle": BracketsAngle,
  "brackets-curly": BracketsCurly,
  "brackets-square": BracketsSquare,
  "calendar-dots": CalendarDots,
  "cards-three": CardsThree,
  "caret-down": CaretDown,
  "certificate": Certificate,
  "chart-bar": ChartBar,
  "circle-half": CircleHalf,
  "clipboard-text": ClipboardText,
  "clock-countdown": ClockCountdown,
  "clock-counter-clockwise": ClockCounterClockwise,
  "cloud-arrow-down": CloudArrowDown,
  "code": Code,
  "copy": Copy,
  "cube": Cube,
  "cube-transparent": CubeTransparent,
  "database": Database,
  "diamonds-four": DiamondsFour,
  "download-simple": DownloadSimple,
  "eraser": Eraser,
  "eye-slash": EyeSlash,
  "eyedropper": Eyedropper,
  "file-code": FileCode,
  "file-js": FileJs,
  "file-pdf": FilePdf,
  "file-py": FilePy,
  "file-text": FileText,
  "fingerprint": Fingerprint,
  "flask": Flask,
  "flow-arrow": FlowArrow,
  "folders": Folders,
  "funnel": Funnel,
  "gear-six": GearSix,
  "git-branch": GitBranch,
  "git-diff": GitDiff,
  "globe-hemisphere-west": GlobeHemisphereWest,
  "graph": Graph,
  "grid-four": GridFour,
  "hash-straight": HashStraight,
  "identification-card": IdentificationCard,
  "image": Image,
  "infinity": Infinity,
  "info": Info,
  "key": Key,
  "lightning": Lightning,
  "link": Link,
  "link-break": LinkBreak,
  "link-simple": LinkSimple,
  "list": List,
  "list-bullets": ListBullets,
  "magnifying-glass": MagnifyingGlass,
  "number-square-two": NumberSquareTwo,
  "paint-brush": PaintBrush,
  "paint-brush-broad": PaintBrushBroad,
  "paper-plane-tilt": PaperPlaneTilt,
  "password": Password,
  "path": Path,
  "pencil-simple": PencilSimple,
  "play": Play,
  "plugs": Plugs,
  "plus": Plus,
  "qr-code": QrCode,
  "quotes": Quotes,
  "ruler": Ruler,
  "scribble": Scribble,
  "seal-check": SealCheck,
  "shield-check": ShieldCheck,
  "shipping-container": ShippingContainer,
  "shuffle": Shuffle,
  "sidebar-simple": SidebarSimple,
  "sliders": Sliders,
  "square": Square,
  "star": Star,
  "table": Table,
  "terminal-window": TerminalWindow,
  "text-aa": TextAa,
  "text-align-left": TextAlignLeft,
  "text-h": TextH,
  "timer": Timer,
  "trash": Trash,
  "tree-structure": TreeStructure,
  "tree-view": TreeView,
  "warning-circle": WarningCircle,
  "wifi-slash": WifiSlash,
  "wrench": Wrench,
  "x": X,
};

export const FALLBACK_ICON = Wrench;
