// Generates src/components/icon-data.ts from @phosphor-icons/react: only the
// weights the app uses (duotone everywhere, fill for toggled stars), as raw
// SVG inner markup. Run after adding an icon to ICON_NAMES in icons.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as P from "@phosphor-icons/react/dist/ssr";

const src = readFileSync(new URL("../src/components/icons.ts", import.meta.url), "utf8");
const names = [...src.matchAll(/^  "([a-z0-9-]+)",?$/gm)].map((m) => m[1]);
const pascal = (k) => k.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join("");
const inner = (Cmp, weight) => renderToStaticMarkup(createElement(Cmp, { weight })).replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");

const FILL_NAMES = new Set(["star"]);
const duo = {}, fill = {};
for (const n of names) {
  const Cmp = P[pascal(n)];
  if (!Cmp) throw new Error(`No Phosphor icon for ${n}`);
  duo[n] = inner(Cmp, "duotone");
  if (FILL_NAMES.has(n)) fill[n] = inner(Cmp, "fill");
}
const out = `// Generated by scripts/icons.mjs — do not edit by hand.
export const DUOTONE: Record<string, string> = ${JSON.stringify(duo)};
export const FILL: Record<string, string> = ${JSON.stringify(fill)};
`;
writeFileSync(new URL("../src/components/icon-data.ts", import.meta.url), out);
console.log(`icons: ${names.length} → ${(out.length / 1024).toFixed(0)} KB`);
